# Generated by Django 6.0.1 on 2026-01-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('temperature', models.FloatField(verbose_name='Температура, °C')),
                ('pressure', models.FloatField(verbose_name='Тиск, мм рт. ст.')),
                ('wind_speed', models.FloatField(verbose_name='Швидкість вітру, м/с')),
                ('precipitation', models.FloatField(verbose_name='Ймовірність опадів, %')),
            ],
        ),
    ]
